chrome_pages = {
    "chrome://about/": "Lists all internal Chrome URLs.",
    "chrome://accessibility/": "Access accessibility settings and debugging.",
    "chrome://appcache-internals/": "View app cache internals.",
    "chrome://apps/": "Opens the apps page.",
    "chrome://autofill-internals/": "View Autofill internal details.",
    "chrome://bookmarks/": "Opens the bookmarks manager.",
    "chrome://chrome-urls/": "Lists all internal Chrome URLs.",
    "chrome://components/": "View and update individual components.",
    "chrome://conflicts/": "View conflicts with other software.",
    "chrome://crashes/": "View information about crashes.",
    "chrome://credits/": "View Chrome's credits page.",
    "chrome://device-log/": "View device log.",
    "chrome://dino/": "Opens the offline dinosaur game.",
    "chrome://discards/": "View and manage tab discarding details.",
    "chrome://downloads/": "Opens the downloads page.",
    "chrome://extensions/": "Manage Chrome extensions.",
    "chrome://flags/": "Access experimental features.",
    "chrome://flags/#automatic-tab-discarding": "Access the experimental feature to enable or disable automatic tab discarding.",
    "chrome://flash/": "View details about Flash Player.",
    "chrome://gcm-internals/": "View Google Cloud Messaging internals.",
    "chrome://gpu/": "View information about the GPU.",
    "chrome://histograms/": "View Chrome histograms.",
    "chrome://history/": "Opens the browsing history.",
    "chrome://indexeddb-internals/": "View IndexedDB details.",
    "chrome://inspect/": "Inspect devices and apps.",
    "chrome://interstitials/": "View interstitials.",
    "chrome://media-internals/": "View media internals.",
    "chrome://net-export/": "Export network logs.",
    "chrome://net-internals/": "Access network internals.",
    "chrome://network-errors/": "View network errors.",
    "chrome://newtab/": "Opens a new tab.",
    "chrome://omnibox/": "View omnibox (address bar) debugging information.",
    "chrome://password-manager-internals/": "View password manager details.",
    "chrome://policy/": "View and manage policies.",
    "chrome://predictors/": "View predictors.",
    "chrome://prefs-internals/": "View preferences internals.",
    "chrome://print/": "Opens the print dialog.",
    "chrome://quota-internals/": "View quota details.",
    "chrome://safe-browsing/": "View Safe Browsing details.",
    "chrome://serviceworker-internals/": "View service workers details.",
    "chrome://settings/": "Opens the settings page.",
    "chrome://signin-internals/": "View sign-in internals.",
    "chrome://site-engagement/": "View site engagement metrics.",
    "chrome://suggestions/": "View suggestions.",
    "chrome://sync-internals/": "View sync internals.",
    "chrome://system/": "View system information.",
    "chrome://terms/": "View Chrome’s terms of service.",
    "chrome://translate-internals/": "View translate internals.",
    "chrome://ukm/": "View UKM details.",
    "chrome://usb-internals/": "View USB device information.",
    "chrome://version/": "View the Chrome version and details.",
    "chrome://webrtc-internals/": "View WebRTC internals.",
    "chrome://webrtc-logs/": "View WebRTC logs.",
}
